// Actual Dashboard render and price-update functions, no external scripts/network.
const fs=require('fs'),path=require('path'),assert=require('assert');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'..','Dashboard.html'),'utf8').replace(/<script[^>]*\bsrc=[^>]*>\s*<\/script>/g,'').replace(/<link[^>]*>/g,'');
const series=()=>({setData(){},applyOptions(){},setMarkers(){}});
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'http://localhost/',beforeParse(w){w.fetch=()=>new Promise(()=>{});w.Chart=function(){this.destroy=()=>{}};w.LightweightCharts={createChart:()=>({addCandlestickSeries:series,addLineSeries:series,addHistogramSeries:series,priceScale:()=>({applyOptions(){}}),timeScale:()=>({fitContent(){}}),applyOptions(){},remove(){}})};}});
const w=dom.window,txt=id=>w.document.getElementById(id).textContent;
function payload(){return {symbol:'JIOFIN',frame_exchange:'BSE',requested_exchange:'BSE',analysis_source:'TradingView Direct (BSE)',quote_source:'yahoo.bo',data_source:'yahoo.bo',price:215,frame_close:214.8,analysis_session:'2026-10-09',quote_time:'2026-10-09 15:15:00',feed_state:'CLOSED',feed_label:'MARKET CLOSED',ensemble:{score:54,tradeable:false,action:'WATCHLIST',calibration:{ready:false,exchange:'BSE',note:'UNFITTED — JIOFIN outside supported universe',bars_available:300,bars_required:250,remediation:'A rebuild will not add this symbol.'}},risk:{direction:'NONE',qty:0,plan_available:false,sl:202,t1:227,entry_zone:'213-216',trail_sl_plan:'Move stop to cost',cost:{targets_net_pct:{t1:5}}},kpi:{},chart:[]};}
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
try{
 test('Initial price and independent history provenance visible before first tick',()=>{w.render(payload());assert(txt('activeEngineTag').includes('Quote: yahoo.bo'));assert(txt('liveSrc').includes('Quote: yahoo.bo'));assert(txt('liveSrc').includes('15:15:00'));assert(txt('historySource').includes('TradingView Direct (BSE)'));});
 test('Quote updates synchronize both source labels without overwriting history',()=>{w.paintTick({price:214.8,source:'TradingView Direct (BSE)',quote_time:'2026-10-09 (daily close)',feed_state:'CLOSED'});assert(txt('activeEngineTag').includes('TradingView Direct (BSE)'));assert(txt('liveSrc').includes('TradingView Direct (BSE)'));assert(txt('historySource').includes('frame close ₹214.8'));});
 test('Matching exchange alone never claims a valid calibration',()=>{assert(txt('exchWarn').includes('UNFITTED'));assert(!txt('exchWarn').includes('rank fitted on'));assert(!txt('exchWarn').includes('01-Oct'));});
 test('No duplicated UNFITTED and no blind build command for unknown coverage',()=>{assert.equal((txt('scoreCalNote').match(/UNFITTED/g)||[]).length,1);assert(!txt('scoreCalNote').includes('build_score_calibration'));assert(txt('scoreCalNote').includes('will not add'));});
 test('NONE hides injected stale long-shaped levels and instructions',()=>{assert(txt('targetsBox').includes('NO DIRECTIONAL PLAN'));assert(!txt('targetsBox').includes('213-216'));assert(!txt('targetsBox').includes('Move stop'));assert(!txt('riskPlan').includes('Targets NET'));assert(!txt('aiVerdict').includes('Risk Plan (illustrative)'));});
 test('Ready BSE calibration properly disclosed but still not trade permission',()=>{let d=payload();d.ensemble.calibration.ready=true;d.ensemble.calibration.thresholds={};w.render(d);assert(txt('exchWarn').includes('rank fitted on BSE'));assert(txt('targetsBox').includes('NO DIRECTIONAL PLAN'));});
 test('Legitimate research geometry only when fit and explicit direction present',()=>{let d=payload();d.ensemble.calibration.ready=true;d.ensemble.calibration.thresholds={};d.risk.direction='LONG';d.risk.plan_available=true;d.risk.exec_status='RESEARCH ONLY / NO EXECUTABLE ORDER';w.render(d);assert(txt('targetsBox').includes('Illustrative entry zone'));assert(txt('targetsBox').includes('RESEARCH ONLY'));});
 test('NSE switch clears BSE banner and provenance',()=>{let d=payload();d.frame_exchange=d.requested_exchange='NSE';d.analysis_source='TradingView Direct (NSE)';d.quote_source='yahoo.ns';d.ensemble.calibration.exchange='NSE';w.render(d);assert.equal(w.document.getElementById('exchWarn').style.display,'none');assert(txt('historySource').includes('(NSE)'));assert(!txt('historySource').includes('(BSE)'));assert(txt('activeEngineTag').includes('yahoo.ns'));});
 test('Provenance text cannot inject markup',()=>{let d=payload();d.analysis_source='<img src=x onerror="window.pwned=1">';w.render(d);assert(!w.document.querySelector('#historySource img'));assert(!w.pwned);assert(txt('historySource').includes('<img'));});
 test('Archived study cannot claim current validation',()=>{let d=payload();d.ml={available:true};d.ml_study={ready:true,rebuild_required:true,edge_found:true};w.render(d);assert(txt('mlBox').includes('ARCHIVED OOS study — NOT current validation'));});
 test('A fitted AVOID band explains NONE without claiming missing calibration',()=>{let d=payload();d.ensemble.action='AVOID';d.ensemble.calibration.ready=true;w.render(d);assert(txt('targetsBox').includes('Fitted rank band AVOID'));assert(!txt('targetsBox').includes('Calibration unavailable'));});
 test('Own-history rank is separate from pooled FIT and leaves plan closed',()=>{let d=payload();d.ensemble.own_history={ready:true,status:'READY',relative_rank_pct:76,sessions:250,symbol:'PRAKASH',exchange:'BSE',first_session:'2025-10-06',asof_session:'2026-10-08',reference_session:'2026-10-09'};w.render(d);assert(txt('scoreCalNote').includes('OWN-HISTORY percentile: 76%'));assert(txt('scoreCalNote').includes('NOT cross-stock rank'));assert(!txt('scoreCalNote').includes('Score FIT'));assert(!txt('scoreCalNote').includes('UNFITTED'));assert(txt('exchWarn').includes('Own-history'));assert(txt('targetsBox').includes('NO DIRECTIONAL PLAN'));});
 test('Short own-history requirement and reason are visible',()=>{let d=payload();d.ensemble.own_history={ready:false,status:'INSUFFICIENT_HISTORY',reason:'Do not pad history',bars_available:245,bars_required:500};w.render(d);assert(txt('scoreCalNote').includes('245/500'));assert(txt('scoreCalNote').includes('INSUFFICIENT_HISTORY'));});
 test('Study selected-stock exclusion is explicit and safely escaped',()=>{let d=payload();d.ml={available:true};d.ml_study={ready:true,rebuild_required:true,selected_symbol_note:'Selected stock not included in this study <img src=x onerror="window.pwned=1">'};w.render(d);assert(txt('mlBox').includes('not included in this study'));assert(!w.document.querySelector('#mlBox img'));assert(!w.pwned);});
 console.log(`${n}/${n} FIX103 render cases passed`);
}finally{dom.window.close();}
